meta_product_name: "PintPal"
meta_title: "PintPal"
meta_description: "Quick and easy app for finding Pubs, Bars, and Restaurants with heated outdoor areas"
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards